GerenciadorCondominios/Controllers/VeiculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorCondominios.BLL.Models;
using GerenciadorCondominios.DAL;
using GerenciadorCondominios.DAL.Repositorios;
using GerenciadorCondominios.DAL.Interfaces;

namespace GerenciadorCondominios.Controllers
{
    public class VeiculosController : Controller
    {
        private readonly IVeiculoRepositorio _veiculoRepositorio;
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        public VeiculosController(IVeiculoRepositorio veiculoRepositorio, IUsuarioRepositorio usuarioRepositorio)
        {
            this._veiculoRepositorio = veiculoRepositorio;
            this._usuarioRepositorio = usuarioRepositorio;
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VeiculoId,Nome,Marca,Cor,Placa,UsuarioId")] Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                Usuario usuario = await _usuarioRepositorio.PegarUsuarioPeloNome(User);
                veiculo.UsuarioId = usuario.Id;
                await _veiculoRepositorio.Inserir(veiculo);
                return RedirectToAction("MinhasInformacoes", "Usuarios");
            }
            return View(veiculo);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var veiculo = await _veiculoRepositorio.PegarPeloId(id);
            if (veiculo == null)
            {
                return NotFound();
            }

            return View(veiculo);
        }

        
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("VeiculoId,Nome,Marca,Cor,Placa,UsuarioId")] Veiculo veiculo)
        {
            if (id != veiculo.VeiculoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _veiculoRepositorio.Atualizar(veiculo);
                return RedirectToAction("MinhasInformacoes", "Usuarios");
            }
            return View(veiculo);
        }

        
        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            await _veiculoRepositorio.Excluir(id);
            return Json("Veículo excluido com sucesso!!!");
        }

    }
}

GerenciadorCondominios/Views/Shared/Components/Veiculos/Default.cshtml
@model IEnumerable<GerenciadorCondominios.BLL.Models.Veiculo>

<div class="collection with-header">
    <div class="collection-header">
        <div class="row">
            <div class="col s10">
                <h6>Meus veículos</h6>
            </div>
            <div class="col s2">
                <a asp-controller="Veiculos" asp-action="Create" class="waves-effect waves-light bnt-small btn-floating green darken-4 tooltip" data-position="right" data-tooltip="Novo Veículo">
                    <i class="material-icons">add</i>
                </a>
            </div>
        </div>
    </div>
    <div class="collection-item">
        <table class="stripped highlight responsive">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Marca)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cor)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Placa)
                    </th>

                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Marca)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Placa)
                        </td>
                        <td>
                            <a asp-controller="Veiculos" asp-action="Edit" asp-route-id="@item.VeiculoId" class="btn-floating btn-small blue darken-4 tooltip" data-position="right" data-tooltip="Atualizar Veículo">
                                <i class="material-icons">mode_edit</i>
                            </a> |
                            <a onclick="ConfirmarExclusao(@item.VeiculoId, '@item.Nome')" class="btn-floating btn-small red darken-4 tooltip modal-trigger" data-position="right" data-target="modal" data-tooltip="Excluir Veículo">
                                <i class="material-icons">delete_forever</i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>