GerenciadorCondominios/Controllers/EventosController.cs
using GerenciadorCondominios.BLL.Models;
using GerenciadorCondominios.DAL.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GerenciadorCondominios.Controllers
{
    [Authorize]
    public class EventosController : Controller
    {
        private readonly IEventoRepositorio _eventoRepositorio;
        private readonly IUsuarioRepositorio _usuarioRepositorio;

        public EventosController(IEventoRepositorio eventoRepositorio, IUsuarioRepositorio usuarioRepositorio)
        {
            _eventoRepositorio = eventoRepositorio;
            _usuarioRepositorio = usuarioRepositorio;
        }

        // GET: Eventos
        public async Task<IActionResult> Index()
        {
            Usuario usuario = await _usuarioRepositorio.PegarUsuarioPeloNome(User);

            if (await _usuarioRepositorio.VerificarSeUsuarioEstaEmFuncao(usuario, "Morador"))
            {
                return View(await _eventoRepositorio.PegarEventosPeloId(usuario.Id));
            }
            return View(await _eventoRepositorio.PegarTodos());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            Usuario usuario = await _usuarioRepositorio.PegarUsuarioPeloNome(User);
            Evento evento = new Evento
            {
                UsuarioId = usuario.Id
            };

            return View(evento);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventoId,Nome,Data,UsuarioId")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                await _eventoRepositorio.Inserir(evento);
                TempData["NovoRegistro"] = $"Evento {evento.Nome} inserido com sucesso";
                return RedirectToAction(nameof(Index));
            }

            return View(evento);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Evento evento = await _eventoRepositorio.PegarPeloId(id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventoId,Nome,Data,UsuarioId")] Evento evento)
        {
            if (id != evento.EventoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _eventoRepositorio.Atualizar(evento);
                TempData["Atualizacao"] = $"Evento {evento.Nome} atualizado";
                return RedirectToAction(nameof(Index));
            }

            return View(evento);
        }


        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            await _eventoRepositorio.Excluir(id);
            TempData["Exclusao"] = $"Evento excluído";
            return Json("Evento excluído");
        }
    }
}

GerenciadorCondominios/Views/Shared/_Confirmacoes.cshtml
@if (TempData["NovoRegistro"] != null)
{
    <div class="card-panel green darken-3 valign-wrapper white-text">
        <div class="col s1">
            <i class="material-icons">check_box</i>
        </div>

        <div class="col s11">
            @TempData["NovoRegistro"].ToString()
        </div>
    </div>
}

@if (TempData["Atualizacao"] != null)
{
    <div class="card-panel blue darken-3 valign-wrapper white-text">
        <div class="col s1">
            <i class="material-icons">check_box</i>
        </div>

        <div class="col s11">
            @TempData["Atualizacao"].ToString()
        </div>
    </div>
}

@if (TempData["Exclusao"] != null)
{
    <div class="card-panel red darken-3 valign-wrapper white-text">
        <div class="col s1">
            <i class="material-icons">check_box</i>
        </div>

        <div class="col s11">
            @TempData["Exclusao"].ToString()
        </div>
    </div>
}

GerenciadorCondominios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GerenciadorCondominios</title>
    <environment include="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="~/css/site.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <header>
        <nav class="grey darken-3">
            <div class="nav-wrapper navbar-fixed">
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li class="nav-item"><a class="nav-link" asp-controller="Eventos" asp-action="Index">Meus eventos</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Usuarios" asp-action="MinhasInformacoes">Minhas informacoes</a></li>
                    <li class="nav-item"><partial name="_Logout" /></li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="conteudo-principal">

        <div class="card-body-content">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - GerenciadorCondominios - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    <environment include="Development">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.js"></script>
        <script src="~/js/InicializarTooltips.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.4.1.min.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="~/js/InicializarTooltips.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </environment>
</body>
</html>

GerenciadorCondominios/Views/Shared/_Logout.cshtml
@using Microsoft.AspNetCore.Identity
@using GerenciadorCondominios.BLL.Models
@inject SignInManager<Usuario> SiginManager

@if (SiginManager.IsSignedIn(User))
{
    <form asp-action="Logout" asp-controller="Usuarios" id="formularioLogout">
        <ul>
            <li>
                <a class="nav-link white-text" style="cursor: pointer;" onclick="document.getElementById('formularioLogout').submit();">Logout</a>
            </li>
        </ul>
    </form>
}

GerenciadorCondominios/Views/Shared/_ModalExcluir.cshtml
<div class="modal modal-fixed-footer" style="width:30%;height:30%" id="modal">
   
    <div class="modal-content">
        <h6>Exclusão de registros</h6>
        <p>Prosseguir com a exclusão de <text class="nome"></text> ?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn-small red darken-4 btnExcluir">Sim</button>
        <button type="button" class="btn-small blue darken-4 modal-close">Não</button>
    </div>
</div>